version: '3.8'  # Specify the Compose file format version

services:
  mongodb:
    image: mongo:latest  # Specify the MongoDB image
    container_name: mongo_container  # Name of the container
    ports:
      - "27017:27017"  # Map the host port to the container port
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Set the root username
      MONGO_INITDB_ROOT_PASSWORD: example  # Set the root password
    volumes:
      - mongo_data:/data/db  # Persist data in a named volume

volumes:
  mongo_data:  # Named volume to persist MongoDB data
